spring.config.import=optional:file:.env.local[.properties]

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.dropit=DEBUG

management.endpoint.health.show-details=always

# Convert the values loaded from .env.local into
# Spring Cloud AWS static credential properties
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}