apiVersion: 1

datasources:
  - name: k6 InfluxDB
    uid: k6-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: false
    jsonData:
      httpMode: GET
      timeInterval: 1s

  - name: Application Prometheus
    uid: application-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 2s
